//
// Copyright (c) 2019 Fajar van Megen
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

part of nem2_sdk_dart.sdk.api.model;

class Cosignature {
  /* Hash of parent aggregate transaction that has been signed by a cosignatory of the transaction. */
  String parentHash;

/* Signatures generated by signing the parent aggregate transaction hash. */
  String signature;

/* Signer of the transaction. */
  String signer;

  Cosignature();

  @override
  String toString() {
    return 'Cosignature[parentHash=$parentHash, signature=$signature, signer=$signer, ]';
  }

  Cosignature.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    parentHash = json['parentHash'];
    signature = json['signature'];
    signer = json['signer'];
  }

  Map<String, dynamic> toJson() {
    return {'parentHash': parentHash, 'signature': signature, 'signer': signer};
  }

  static List<Cosignature> listFromJson(List<dynamic> json) {
    return json == null
        ? <Cosignature>[]
        : json.map((value) => new Cosignature.fromJson(value)).toList();
  }

  static Map<String, Cosignature> mapFromJson(Map<String, Map<String, dynamic>> json) {
    var map = <String, Cosignature>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((key, value) => map[key] = new Cosignature.fromJson(value));
    }
    return map;
  }
}
